# ************************************************************************
#  @author:     Andreas Kaeberlein
#  @copyright:  Copyright 2021
#  @credits:    AKAE
#
#  @license:    BSDv3
#  @maintainer: Andreas Kaeberlein
#  @email:      andreas.kaeberlein@web.de
#
#  @file:       unittest.yml
#  @date:       2021-08-25
#
#  @brief:      runs test and deploy
#
# ************************************************************************


name: Unittest

on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ghdl/setup-ghdl-ci@nightly
        with:
          backend: mcode
      - name: Prepare
        run: |
          ghdl --version
          mkdir -p ./sim/work
      - name: eSpiStaticSlave
        run: |
          ghdl -a --std=93c --workdir=./sim/work ./bfm/eSpiStaticSlave.vhd
          ghdl -a --std=93c --workdir=./sim/work ./tb/eSpiStaticSlave_tb.vhd
          ghdl -r --std=93c --workdir=./sim/work eSpiStaticSlave
          ghdl -r --std=93c --workdir=./sim/work eSpiStaticSlave_tb
          [[ -z $($(ghdl -e --workdir=./sim/work eSpiStaticSlave_tb) | grep "Test SUCCESSFUL") ]] && echo "FAIL" && exit 1
